version: "3"
services:
  postgres:
    image: postgres:16
    volumes:
      - "data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=pgsupa
      - POSTGRES_DB=pgdbh
      - POSTGRES_PASSWORD=2rJVjFCvD9weYKxd7AkftPyw6BsgJpUevmA
    ports:
      - "3405:5432"
    healthcheck:
      test: [
          "CMD-SHELL",
          "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"
        ]
      interval: 30s
      retries: 3
  prest:
    # use latest build - analyze the risk of using this version in production
    build: .

    environment:
      #- PREST_PG_URL=postgres://username:password@hostname:port/dbname
      - PREST_PG_URL=postgres://pgsupa:2rJVjFCvD9weYKxd7AkftPyw6BsgJpUevmA@185.94.29.87:3405/pgdbh
      - PREST_DEBUG=false
      - PREST_AUTH_ENABLED=true
      - PREST_CACHE_ENABLED=false
  
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3080:3000"

volumes:
  data: